#!/bin/sh
#
# This first script finds all the directories in the given folder and runs the
# crawl script on them to find media files.
#

if [ -z "$1" ]; then
	echo "usage: `basename $0` path"
	exit 1
fi

bin=`dirname "$0"`
target_path="${1}YOG"

find "$1" -type d | while read path; do
	$bin/yog-crawl-directory "$path" "$target_path"
done
