#!/bin/sh
# vim: ft=html

if [ -z "$1" ]; then
	echo "usage: `basename $0` path"
	exit 1
fi

bin=`dirname "$0"`
directory="$1"
metapath="$directory/metadata.txt"
subdirectories="$directory/subdirectories.txt"

if [ -e $subdirectories ] ; then
  rm $subdirectories
fi
echo "<hr><pre><a href="../">..</a>" > $subdirectories
find "$1" -maxdepth 1 -type d | grep -Ev "(thumbs|web)" | while read subdir; do
  echo "<a href="$subdir/">$subdir</a>" >> $subdirectories
done
echo "</pre>" >> $subdirectories

if [ -e "$subdirectories" ]; then
  sudirs=`cat $subdirectories`
fi

if [ -e "$metapath" ]; then
	intro=`cat $metapath`
fi

cat <<EOF
<html>
    <body>
        <style type="text/css">
            body {
                background-color: #aaa;
                font-family: sans, helvetica, arial;
            }
            div.image-container {
                width: 220px;
                height: 400px;
                float: left;
                text-align: center;
            }
            img {
                padding: 4px;
                border: 1px solid #777;
                background-color: white;
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            img:hover {
                border: 1px solid white;
            }
            a {
                color: black;
                text-decoration: none;
            }
            a:hover {
                color: #fff;
                text-decoration: none;
            }
            h1 {
                color: blue;
                margin-left: auto;
                margin-right: auto;
            }
        </style>

        <p>${subdirs}</p>

        <p>${intro}</p>
        <p></p>
EOF
