#!/bin/sh
#
# If the file exists and was successfully converted into a thumbnail and web
# size image, return its filename.
#

if [ -z "$2" ]; then
	echo "usage: `basename $0` filepath target_path" >&2
	exit 1
fi

bin=`dirname "$0"`
filepath="$1"
target_path="$2"
filename=`basename "$filepath"`

mkdir -p "$target_path/thumbs" "$target_path/web"

if ! $bin/yog-create-thumbnail "$filepath" "$target_path/thumbs"; then
	exit 1
fi

if ! $bin/yog-create-web-image "$filepath" "$target_path/web"; then
	exit 1
fi

exit 0
