#!/bin/sh
#
# Crawl a given directory for media files and generate an index.html file in
# this directory.
#

if [ -z "$2" ]; then
	echo "usage: `basename $0` path target_path"
	exit 1
fi

bin=`dirname "$0"`
directory="$1"
target_path="$2"
index="$target_path/index.html"

mkdir -p "$target_path"

$bin/yog-html-header "$directory" > "$index"

$bin/yog-find-media "$directory" | while read filepath; do
	if $bin/yog-process-file "$filepath" "$target_path"; then
		$bin/yog-html-media "$filepath" >> "$index"
	fi
done

$bin/yog-html-footer >> "$index"

chmod 644 "$index"
