#!/bin/sh
#
# Generate a thumbnail size image for the given media.
#

if [ -z "$2" ]; then
	echo "usage: `basename $0` filepath target_path" >&2
	exit 1
fi

filepath="$1"
target_path="$2"
filename=`basename "$filepath"`
target="$target_path/${filename}.jpg"

# Already exists.
if [ -e "$target" ]; then
	exit 0
fi

if ! convert -auto-orient -resize 200x200 "$filepath[0]" "$target" >/dev/null 2>/dev/null; then
	echo "yog-create-thumbnail: unable to process $filepath" >&2
	exit 1
fi

chmod 644 "$target"

exit 0
