#!/bin/sh
#
# Crawl a given directory for media files and generate an index.html file in
# this directory.
#

if [ -z "$1" ]; then
	echo "usage: `basename $0` path target_path"
	exit 1
fi

bin=`dirname "$0"`
directory="$1"
target="$2"
indexdir="$target/`basename $directory`"
index="$indexdir/index.html"

echo $index
echo $directory
exit 0

mkdir -p $indexdir
$bin/yog-html-header "$directory" > "$index"

$bin/yog-find-media "$directory" | while read filepath; do
	if $bin/yog-process-file "$filepath" "$target"; then
		$bin/yog-html-media "$filepath" >> "$index"
	fi
done

$bin/yog-html-footer >> "$index"

chmod 644 "$index"
