#!/bin/sh
# vim: ft=html

if [ -z "$1" ]; then
	echo "usage: `basename $0` path"
	exit 1
fi

bin=`dirname "$0"`
directory="$1"
metapath="$directory/metadata.txt"

if [ -e "$metapath" ]; then
	intro=`cat $metapath`
fi

cat <<EOF
<html>
    <body>
        <style type="text/css">
            body {
                background-color: #aaa;
                font-family: sans, helvetica, arial;
            }
            div.image-container {
                width: 220px;
                height: 400px;
                float: left;
                text-align: center;
            }
            img {
                padding: 4px;
                border: 1px solid #777;
                background-color: white;
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            img:hover {
                border: 1px solid white;
            }
            a {
                color: black;
                text-decoration: none;
            }
            a:hover {
                color: #fff;
                text-decoration: none;
            }
            h1 {
                color: blue;
                margin-left: auto;
                margin-right: auto;
            }
        </style>

        <h1>${intro}</h1>
EOF
